theme: minima
title: Frederik Bous
description: >
  Researcher in voice synthesis
  and music informatics.
  I'm interested in developing tools
  for computer music
  and related artistic fields.
collections_dir: collections
collections:
  publications:
    title: true
    type: true
    output: true
plugins:
  - jekyll-redirect-from
